use lazy_static::lazy_static;
use std::collections::HashMap;

lazy_static! {
    pub static ref COUNTRIES: HashMap<&'static str, &'static str> = {
        HashMap::from([
            ("Andorra", "AD"),
            ("United Arab Emirates", "AE"),
            ("Afghanistan", "AF"),
            ("Antigua and Barbuda", "AG"),
            ("Anguilla", "AI"),
            ("Albania", "AL"),
            ("Armenia", "AM"),
            ("Angola", "AO"),
            ("Antarctica", "AQ"),
            ("Argentina", "AR"),
            ("American Samoa", "AS"),
            ("Austria", "AT"),
            ("Australia", "AU"),
            ("Aruba", "AW"),
            ("Aland Islands", "AX"),
            ("Azerbaijan", "AZ"),
            ("Bosnia and Herzegovina", "BA"),
            ("Barbados", "BB"),
            ("Bangladesh", "BD"),
            ("Belgium", "BE"),
            ("Burkina Faso", "BF"),
            ("Bulgaria", "BG"),
            ("Bahrain", "BH"),
            ("Burundi", "BI"),
            ("Benin", "BJ"),
            ("Saint Barthelemy", "BL"),
            ("Bermuda", "BM"),
            ("Brunei", "BN"),
            ("Bolivia", "BO"),
            ("Caribbean Netherlands", "BQ"),
            ("Brazil", "BR"),
            ("Bahamas", "BS"),
            ("Bhutan", "BT"),
            ("Bouvet Island", "BV"),
            ("Botswana", "BW"),
            ("Belarus", "BY"),
            ("Belize", "BZ"),
            ("Canada", "CA"),
            ("Cocos Islands", "CC"),
            ("Democratic Republic of the Congo", "CD"),
            ("Central African Republic", "CF"),
            ("Republic of the Congo", "CG"),
            ("Switzerland", "CH"),
            ("Ivory Coast", "CI"),
            ("Cook Islands", "CK"),
            ("Chile", "CL"),
            ("Cameroon", "CM"),
            ("China", "CN"),
            ("Colombia", "CO"),
            ("Costa Rica", "CR"),
            ("Cuba", "CU"),
            ("Cape Verde", "CV"),
            ("Curacao", "CW"),
            ("Christmas Island", "CX"),
            ("Cyprus", "CY"),
            ("Czech Republic", "CZ"),
            ("Germany", "DE"),
            ("Djibouti", "DJ"),
            ("Denmark", "DK"),
            ("Dominica", "DM"),
            ("Dominican Republic", "DO"),
            ("Algeria", "DZ"),
            ("Ecuador", "EC"),
            ("Estonia", "EE"),
            ("Egypt", "EG"),
            ("Western Sahara", "EH"),
            ("Eritrea", "ER"),
            ("Spain", "ES"),
            ("Ethiopia", "ET"),
            ("Finland", "FI"),
            ("Fiji", "FJ"),
            ("Falkland Islands", "FK"),
            ("Micronesia", "FM"),
            ("Faroe Islands", "FO"),
            ("France", "FR"),
            ("Gabon", "GA"),
            ("United Kingdom", "GB"),
            ("Grenada", "GD"),
            ("Georgia", "GE"),
            ("French Guiana", "GF"),
            ("Guernsey", "GG"),
            ("Ghana", "GH"),
            ("Gibraltar", "GI"),
            ("Greenland", "GL"),
            ("Gambia", "GM"),
            ("Guinea", "GN"),
            ("Guadeloupe", "GP"),
            ("Equatorial Guinea", "GQ"),
            ("Greece", "GR"),
            ("South Georgia and the South Sandwich Islands", "GS"),
            ("Guatemala", "GT"),
            ("Guam", "GU"),
            ("Guinea-Bissau", "GW"),
            ("Guyana", "GY"),
            ("Hong Kong", "HK"),
            ("Heard Island and McDonald Islands", "HM"),
            ("Honduras", "HN"),
            ("Croatia", "HR"),
            ("Haiti", "HT"),
            ("Hungary", "HU"),
            ("Indonesia", "ID"),
            ("Ireland", "IE"),
            ("Israel", "IL"),
            ("Isle of Man", "IM"),
            ("India", "IN"),
            ("British Indian Ocean Territory", "IO"),
            ("Iraq", "IQ"),
            ("Iran", "IR"),
            ("Iceland", "IS"),
            ("Italy", "IT"),
            ("Jersey", "JE"),
            ("Jamaica", "JM"),
            ("Jordan", "JO"),
            ("Japan", "JP"),
            ("Kenya", "KE"),
            ("Kyrgyzstan", "KG"),
            ("Cambodia", "KH"),
            ("Kiribati", "KI"),
            ("Comoros", "KM"),
            ("Saint Kitts and Nevis", "KN"),
            ("North Korea", "KP"),
            ("South Korea", "KR"),
            ("Kuwait", "KW"),
            ("Cayman Islands", "KY"),
            ("Kazakhstan", "KZ"),
            ("Laos", "LA"),
            ("Lebanon", "LB"),
            ("Saint Lucia", "LC"),
            ("Liechtenstein", "LI"),
            ("Sri Lanka", "LK"),
            ("Liberia", "LR"),
            ("Lesotho", "LS"),
            ("Lithuania", "LT"),
            ("Luxembourg", "LU"),
            ("Latvia", "LV"),
            ("Libya", "LY"),
            ("Morocco", "MA"),
            ("Monaco", "MC"),
            ("Moldova", "MD"),
            ("Montenegro", "ME"),
            ("Saint Martin", "MF"),
            ("Madagascar", "MG"),
            ("Marshall Islands", "MH"),
            ("North Macedonia", "MK"),
            ("Mali", "ML"),
            ("Myanmar", "MM"),
            ("Mongolia", "MN"),
            ("Macao", "MO"),
            ("Northern Mariana Islands", "MP"),
            ("Martinique", "MQ"),
            ("Mauritania", "MR"),
            ("Montserrat", "MS"),
            ("Malta", "MT"),
            ("Mauritius", "MU"),
            ("Maldives", "MV"),
            ("Malawi", "MW"),
            ("Mexico", "MX"),
            ("Malaysia", "MY"),
            ("Mozambique", "MZ"),
            ("Namibia", "NA"),
            ("New Caledonia", "NC"),
            ("Niger", "NE"),
            ("Norfolk Island", "NF"),
            ("Nigeria", "NG"),
            ("Nicaragua", "NI"),
            ("Netherlands", "NL"),
            ("Norway", "NO"),
            ("Nepal", "NP"),
            ("Nauru", "NR"),
            ("Niue", "NU"),
            ("New Zealand", "NZ"),
            ("Oman", "OM"),
            ("Panama", "PA"),
            ("Peru", "PE"),
            ("French Polynesia", "PF"),
            ("Papua New Guinea", "PG"),
            ("Philippines", "PH"),
            ("Pakistan", "PK"),
            ("Poland", "PL"),
            ("Saint Pierre and Miquelon", "PM"),
            ("Pitcairn", "PN"),
            ("Puerto Rico", "PR"),
            ("Palestine", "PS"),
            ("Portugal", "PT"),
            ("Palau", "PW"),
            ("Paraguay", "PY"),
            ("Qatar", "QA"),
            ("Reunion", "RE"),
            ("Romania", "RO"),
            ("Serbia", "RS"),
            ("Russia", "RU"),
            ("Rwanda", "RW"),
            ("Saudi Arabia", "SA"),
            ("Solomon Islands", "SB"),
            ("Seychelles", "SC"),
            ("Sudan", "SD"),
            ("Sweden", "SE"),
            ("Singapore", "SG"),
            ("Saint Helena", "SH"),
            ("Slovenia", "SI"),
            ("Svalbard and Jan Mayen", "SJ"),
            ("Slovakia", "SK"),
            ("Sierra Leone", "SL"),
            ("San Marino", "SM"),
            ("Senegal", "SN"),
            ("Somalia", "SO"),
            ("Suriname", "SR"),
            ("South Sudan", "SS"),
            ("Sao Tome and Principe", "ST"),
            ("El Salvador", "SV"),
            ("Sint Maarten", "SX"),
            ("Syria", "SY"),
            ("Eswatini", "SZ"),
            ("Turks and Caicos Islands", "TC"),
            ("Chad", "TD"),
            ("French Southern Territories", "TF"),
            ("Togo", "TG"),
            ("Thailand", "TH"),
            ("Tajikistan", "TJ"),
            ("Tokelau", "TK"),
            ("Timor-Leste", "TL"),
            ("Turkmenistan", "TM"),
            ("Tunisia", "TN"),
            ("Tonga", "TO"),
            ("Turkey", "TR"),
            ("Trinidad and Tobago", "TT"),
            ("Tuvalu", "TV"),
            ("Taiwan", "TW"),
            ("Tanzania", "TZ"),
            ("Ukraine", "UA"),
            ("Uganda", "UG"),
            ("United States Minor Outlying Islands", "UM"),
            ("United States", "US"),
            ("Uruguay", "UY"),
            ("Uzbekistan", "UZ"),
            ("Vatican City", "VA"),
            ("Saint Vincent and the Grenadines", "VC"),
            ("Venezuela", "VE"),
            ("British Virgin Islands", "VG"),
            ("United States Virgin Islands", "VI"),
            ("Vietnam", "VN"),
            ("Vanuatu", "VU"),
            ("Wallis and Futuna", "WF"),
            ("Samoa", "WS"),
            ("Yemen", "YE"),
            ("Mayotte", "YT"),
            ("South Africa", "ZA"),
            ("Zambia", "ZM"),
            ("Zimbabwe", "ZW"),
        ])
    };
}

lazy_static! {
    pub static ref COUNTRIES_LOWER: HashMap<String, &'static str> = {
        COUNTRIES
            .iter()
            .map(|(&name, &code)| (name.to_lowercase(), code))
            .collect()
    };
    pub static ref DEMONYMS: HashMap<&'static str, &'static str> = {
        HashMap::from([
            ("afghan", "AF"),
            ("albanian", "AL"),
            ("algerian", "DZ"),
            ("american", "US"),
            ("andorran", "AD"),
            ("angolan", "AO"),
            ("anguillian", "AI"),
            ("argentine", "AR"),
            ("armenian", "AM"),
            ("aruban", "AW"),
            ("australian", "AU"),
            ("austrian", "AT"),
            ("azerbaijani", "AZ"),
            ("bahamian", "BS"),
            ("bahraini", "BH"),
            ("bangladeshi", "BD"),
            ("barbadian", "BB"),
            ("belarusian", "BY"),
            ("belgian", "BE"),
            ("belizean", "BZ"),
            ("beninese", "BJ"),
            ("bermudian", "BM"),
            ("bhutanese", "BT"),
            ("bolivian", "BO"),
            ("bosnian", "BA"),
            ("botswanan", "BW"),
            ("brazilian", "BR"),
            ("british", "GB"),
            ("bruneian", "BN"),
            ("bulgarian", "BG"),
            ("burkinabe", "BF"),
            ("burundian", "BI"),
            ("cambodian", "KH"),
            ("cameroonian", "CM"),
            ("canadian", "CA"),
            ("cape verdian", "CV"),
            ("caymanian", "KY"),
            ("central african", "CF"),
            ("chadian", "TD"),
            ("chilean", "CL"),
            ("chinese", "CN"),
            ("colombian", "CO"),
            ("comoran", "KM"),
            ("congolese", "CG"),
            ("cook islander", "CK"),
            ("costa rican", "CR"),
            ("croatian", "HR"),
            ("cuban", "CU"),
            ("cypriot", "CY"),
            ("czech", "CZ"),
            ("danish", "DK"),
            ("djiboutian", "DJ"),
            ("dominican", "DO"),
            ("dutch", "NL"),
            ("east timorese", "TL"),
            ("ecuadorean", "EC"),
            ("egyptian", "EG"),
            ("emirati", "AE"),
            ("equatorial guinean", "GQ"),
            ("eritrean", "ER"),
            ("estonian", "EE"),
            ("ethiopian", "ET"),
            ("fijian", "FJ"),
            ("filipino", "PH"),
            ("finnish", "FI"),
            ("french", "FR"),
            ("gabonese", "GA"),
            ("gambian", "GM"),
            ("georgian", "GE"),
            ("german", "DE"),
            ("ghanaian", "GH"),
            ("greek", "GR"),
            ("grenadian", "GD"),
            ("guatemalan", "GT"),
            ("guinean", "GN"),
            ("guyanese", "GY"),
            ("haitian", "HT"),
            ("honduran", "HN"),
            ("hungarian", "HU"),
            ("icelander", "IS"),
            ("indian", "IN"),
            ("indonesian", "ID"),
            ("iranian", "IR"),
            ("iraqi", "IQ"),
            ("irish", "IE"),
            ("israeli", "IL"),
            ("italian", "IT"),
            ("ivorian", "CI"),
            ("jamaican", "JM"),
            ("japanese", "JP"),
            ("jordanian", "JO"),
            ("kazakhstani", "KZ"),
            ("kenyan", "KE"),
            ("kuwaiti", "KW"),
            ("kyrgyzstani", "KG"),
            ("laotian", "LA"),
            ("latvian", "LV"),
            ("lebanese", "LB"),
            ("liberian", "LR"),
            ("libyan", "LY"),
            ("lithuanian", "LT"),
            ("luxembourger", "LU"),
            ("macedonian", "MK"),
            ("malagasy", "MG"),
            ("malawian", "MW"),
            ("malaysian", "MY"),
            ("maldivan", "MV"),
            ("malian", "ML"),
            ("maltese", "MT"),
            ("marshallese", "MH"),
            ("mauritanian", "MR"),
            ("mauritian", "MU"),
            ("mexican", "MX"),
            ("micronesian", "FM"),
            ("moldovan", "MD"),
            ("monacan", "MC"),
            ("mongolian", "MN"),
            ("montenegrin", "ME"),
            ("moroccan", "MA"),
            ("mozambican", "MZ"),
            ("namibian", "NA"),
            ("nauruan", "NR"),
            ("nepalese", "NP"),
            ("new zealander", "NZ"),
            ("nicaraguan", "NI"),
            ("nigerian", "NG"),
            ("nigerien", "NE"),
            ("north korean", "KP"),
            ("norwegian", "NO"),
            ("omani", "OM"),
            ("pakistani", "PK"),
            ("palauan", "PW"),
            ("panamanian", "PA"),
            ("papua new guinean", "PG"),
            ("paraguayan", "PY"),
            ("peruvian", "PE"),
            ("polish", "PL"),
            ("portuguese", "PT"),
            ("qatari", "QA"),
            ("romanian", "RO"),
            ("russian", "RU"),
            ("rwandan", "RW"),
            ("salvadoran", "SV"),
            ("sammarinese", "SM"),
            ("samoan", "WS"),
            ("saudi", "SA"),
            ("scottish", "GB"),
            ("senegalese", "SN"),
            ("serbian", "RS"),
            ("seychellois", "SC"),
            ("sierra leonean", "SL"),
            ("singaporean", "SG"),
            ("slovak", "SK"),
            ("slovene", "SI"),
            ("somali", "SO"),
            ("south african", "ZA"),
            ("south korean", "KR"),
            ("spanish", "ES"),
            ("sri lankan", "LK"),
            ("sudanese", "SD"),
            ("surinamer", "SR"),
            ("swazi", "SZ"),
            ("swedish", "SE"),
            ("swiss", "CH"),
            ("syrian", "SY"),
            ("taiwanese", "TW"),
            ("tajikistani", "TJ"),
            ("tanzanian", "TZ"),
            ("thai", "TH"),
            ("togolese", "TG"),
            ("tongan", "TO"),
            ("tunisian", "TN"),
            ("turkish", "TR"),
            ("turkmen", "TM"),
            ("tuvaluan", "TV"),
            ("ugandan", "UG"),
            ("ukrainian", "UA"),
            ("uruguayan", "UY"),
            ("uzbekistani", "UZ"),
            ("vanuatuan", "VU"),
            ("venezuelan", "VE"),
            ("vietnamese", "VN"),
            ("welsh", "GB"),
            ("yemeni", "YE"),
            ("zambian", "ZM"),
            ("zimbabwean", "ZW"),
        ])
    };
}
